import os
import click
import sys
import time
import shutil
import logging
import numpy as np
import pandas as pd
from pathlib import Path
from utils import init_logger
from sklearn.preprocessing import quantile_transform

def add_analyze_commands(cli):
    @cli.command(name="analyze", help="""Analyze MS search results generated by the Validate module. 

                Example: trcirit analyze -i valid_out -o anlyz_out
                """,
                context_settings={'help_option_names': ['-h', '--help']})
    @click.option("--input", "-i", required=True, type=click.Path(exists=True), 
                help="Module Validate output directory")
    @click.option("--out_dir","-o", default="anlyz_out",
                help="Output directory, default: anlyz_out",
                type=click.Path(file_okay=False, dir_okay=True, writable=True, resolve_path=True))
    @click.option("--circ_ref", "-f", required=False,
              type=click.Path(exists=True),
              help="Optional circRNA reference fasta file to extract ORF")

    def cmd_analyze(input, out_dir, circ_ref):

        # Initialize logger at module import
        logger = init_logger("analyze")
        total_start = time.time()
        
        try:
            # === Step 1: analyze proteinGroup.txt ===
            click.echo("Start analyzing...")
            input_path = Path(input).expanduser().resolve()
            protein_group_path = input_path.joinpath("linear_free", "combined", "txt", "proteinGroups.txt")
            check_path(protein_group_path, logger) 

            protein_num, summary_path = analyze_protein(protein_group_path, out_dir, output_prefix="Protein", logger=logger)
            
            if circ_ref:
                fasta_path = Path(circ_ref).expanduser().resolve()
                add_circ_seq_to_summary(summary_path, fasta_path, logger=logger)

            click.secho(f"\nIdentified {protein_num} peptides/proteins!", fg="green")
            click.echo(f"Analyze completed. Files saved to: {out_dir}")
            logger.info(f"Analyze completed. Files saved to: {out_dir}")

            total_time = time.time() - total_start
            click.secho(f"\nPipeline completed in {total_time:.2f} seconds.", fg='green')
        
        except Exception as e:
            click.secho(f"Error: {e}", fg='red', err=True)
            raise click.Abort()
        
    return cli

def check_path(path, logger):
    """Ensure that a given path exists. Raise error if not."""

    p = Path(path).expanduser().resolve()
    if not p.exists():
        raise FileNotFoundError(f"Path does not exist:\n {p}")
    else:
        logger.info(f"Starting solving: {p}")
    return p

def analyze_protein(protein_group_path, out_dir, output_prefix="protein", logger=None):
    """
    Analyze proteinGroup.txt, including protein filtering, normalization and log-transformation.
    """
    
    # === Step 0: ensure output directory exists ===
    os.makedirs(out_dir, exist_ok=True)
    df = pd.read_csv(protein_group_path, sep='\t', low_memory=False)

    # === Step 1: filter invalid rows ===
    click.echo("\n- Filtering low-confidence proteins\n")

    # == filter criteria ==
    is_not_contaminant = df["Potential contaminant"].astype(str).str.strip() != "+"
    is_not_reverse = df["Reverse"].astype(str).str.strip() != "+"
    is_not_OIBS = df["Only identified by site"].astype(str).str.strip() != "+"
    is_qvalue_pass = df["Q-value"] < 0.01
    # is_score_pass = df["Score"] > 70
    is_unique_pep = df["Unique peptides"] >= 1

    # filter rows
    # mask = is_not_contaminant & is_not_reverse & is_qvalue_pass & is_score_pass & is_unique_pep
    mask = is_not_contaminant & is_not_reverse & is_qvalue_pass & is_unique_pep
    df_filtered = df[mask].copy()

    if df_filtered.empty:
        click.echo("[Warning] Analyze stop! After filtering, no high-confidence proteins were identified from proteinGroup.txt.")
        sys.exit(1)

    # === Step2: iBAQ data normalization and transformation ===
    click.echo("===Step1 : iBAQ quantification===")
    click.echo("- iBAQ Normalization and log-transformation")

    ibaq_cols = [col for col in df_filtered.columns if col.startswith("iBAQ ") and col != "iBAQ"]
    df_ibaq = df_filtered[ibaq_cols].copy()

    low_info_rows = df_ibaq[df_ibaq.notna().sum(axis=1) < 3]
    if not low_info_rows.empty:
        logger.warning(f"{low_info_rows.shape[0]} proteins detected in <3 samples and will be excluded")

    df_ibaq = df_ibaq[df_ibaq.notna().sum(axis=1) >= 3] # need to be detected in at least three samples

    # !!!quantile normalization 
    # QN by columns 
    df_qn = pd.DataFrame(
        quantile_transform(df_ibaq.values, axis=0, copy=True),
        index=df_ibaq.index,
        columns=df_ibaq.columns
    )

    # log2 transform
    df_log2 = np.log2(df_qn + 1)

    # fill NA with min per sample
    is_filled = df_log2.isna().any(axis=1)
    min_vals = np.nanmin(df_log2.values, axis=0)
    df_filled = df_log2.fillna(pd.Series(min_vals, index=df_log2.columns))

    # === Step3: write output files ===
    click.echo("- Prepare iBAQ data and write results")

    # 1. IBAQ quantification（normalized, log2, NA filled）
    df_filled_with_name = df_filtered.loc[df_filled.index, ["Protein IDs"]].copy()
    df_quant = pd.concat([df_filled_with_name, df_filled], axis=1)
    df_quant.to_csv(os.path.join(out_dir, f"{output_prefix}_iBAQ_processed.tsv"), sep="\t", index=False)

    # 2. iBAQ raw（only Protein IDs + raw iBAQ）
    df_raw_ibaq = pd.concat([
        df_filtered.loc[df_filled.index, ["Protein IDs"]],
        df_ibaq.loc[df_filled.index]
    ], axis=1)
    df_raw_ibaq.to_csv(os.path.join(out_dir, f"{output_prefix}_iBAQ_raw.tsv"), sep="\t", index=False)

    # 3. Summary（Protein + Gene + iBAQ + Peptides IDs + Peptide seqs + Missing Flag）
    meta_cols = ["Protein IDs", "Fasta headers", "Unique peptides","Score", "iBAQ", "Peptide IDs"]
    df_meta = df_filtered.loc[df_filled.index, meta_cols].copy()
    df_meta["Filled_Missing"] = is_filled.astype(bool).values

    summary_path = os.path.join(out_dir, f"{output_prefix}_summary.tsv")
    df_meta.to_csv(summary_path, sep="\t", index=False)

    peptide_path=os.path.join(os.path.dirname(protein_group_path), "peptides.txt")
    update_summary_with_peptide_seqs(summary_path, peptide_path, logger=logger)

    # 4. LFQ quantification results (LFQ intensity alreay normalized)
    click.echo("\n===Step2 : LFQ quantification===")
    click.echo("- Extract LFQ results and write results")

    lfq_cols = [col for col in df_filtered.columns if col.startswith("LFQ intensity ")]
    if lfq_cols:
        df_lfq = df_filtered[["Protein IDs"] + lfq_cols]
        df_lfq.to_csv(os.path.join(out_dir, f"{output_prefix}_LFQ.tsv"), sep="\t", index=False)
    else:
        click.secho("Warning: No LFQ quantification results found in proteinGroups.txt!", fg="red")

        if logger:
            logger.info("Warning: No LFQ quantification results found in proteinGroups.txt!")

    # 4. write README（README.txt）
    with open(os.path.join(out_dir, "README.txt"), "w") as f:
        f.write(
            "# Output Description for analyze module\n"
            "1. *_iBAQ_quantification.tsv: Protein IDs + iBAQ matrix (quantile normalized across samples, log2-transformed, NA filled).\n"
            "   iBAQ values are suitable for comparing **absolute abundance between different proteins**.\n"
            "2. *_raw.tsv: Protein IDs + raw iBAQ values (not normalized/log2).\n"
            "3. *_LFQ.tsv: Protein IDs + LFQ intensity columns (raw). LFQ values are suitable for comparing **relative abundance across samples for the same protein**.\n"
            "4. *_summary.tsv: Protein summary including gene name, unique peptides, iBAQ, peptide IDs, peptide sequences (Peptide seqs), missing data flag and ORF. Column 'Peptide seqs' is mapped from 'Peptide IDs' using peptides.txt."
            "Column 'Filled_Missing' = True if any iBAQ value was originally missing.\n"
            "5. Fill strategy: missing values are filled with the minimum log2(iBAQ+1) value of each sample (column-wise).\n"
            "6. High-confidence protein criteria:\n"
                "   - Potential contaminant != '+'\n"
                "   - Reverse != '+' \n"
                "   - Only identified by site != '+'\n"
                "   - Q-value < 0.01\n"
                "   - unique peptide >= 1\n"
        )

    return  df_meta.shape[0], summary_path

def update_summary_with_peptide_seqs(summary_path, peptides_path, logger=None):
    """
    Replace 'Peptide IDs' column in summary.tsv with corresponding peptide sequences
    based on peptides.txt file, and generate a new 'Peptide seqs' column.

    Parameters
    ----------
    summary_path : str
        Path to the summary file (must contain 'Peptide IDs' column).
    peptides_path : str
        Path to the MaxQuant peptides.txt file (must contain 'id' and 'Sequence' columns).
    """

    # Step 1: Load summary.tsv
    try:
        df_summary = pd.read_csv(summary_path, sep='\t')
    except Exception as e:
        raise IOError(f"Failed to load summary file: {summary_path}\nError: {e}")

    if "Peptide IDs" not in df_summary.columns:
        raise KeyError("Column 'Peptide IDs' not found in summary file.")

    # Step 2: Load peptides.txt and create mapping from id to peptide sequence
    try:
        df_pep = pd.read_csv(peptides_path, sep='\t', usecols=["id", "Sequence"])
    except Exception as e:
        raise IOError(f"Failed to load peptides.txt: {peptides_path}\nError: {e}")

    id_to_seq = df_pep.set_index("id")["Sequence"].to_dict()

    # Step 3: Define mapping function
    missing_ids = set()

    def map_ids_to_seqs(id_string):
        if pd.isna(id_string):
            return ""
        try:
            id_string = str(id_string)
            ids = [int(x) for x in id_string.split(";") if x.strip().isdigit()]
            seqs = []
            for i in ids:
                seq = id_to_seq.get(i)
                if seq:
                    seqs.append(seq)
                else:
                    missing_ids.add(i)
            return ";".join(seqs)
        except Exception as e:
            print(f"[DEBUG] Failed to parse: {id_string} — Error: {e}")
            return ""
    # Step 4: Apply conversion
    print("[DEBUG] Example Peptide IDs:")
    print(df_summary["Peptide IDs"].dropna().astype(str).unique()[:5])  
    df_summary["Peptide seqs"] = df_summary["Peptide IDs"].apply(map_ids_to_seqs)

    # Step 5: Drop Peptide IDs column, keep column order
    # df_summary = df_summary.drop(columns=["Peptide IDs"])
    if "Filled_Missing" in df_summary.columns:
        cols = [c for c in df_summary.columns if c != "Filled_Missing"] + ["Filled_Missing"]
        df_summary = df_summary[cols]

    # Step 6: Write back to file
    try:
        df_summary.to_csv(summary_path, sep='\t', index=False)
    except Exception as e:
        raise IOError(f"Failed to write updated summary file: {summary_path}\nError: {e}")

    # Step 7: Log missing IDs (if any)
    # some IDs may be filter for low-confidence, so cannot be found in peptides.txt
    if missing_ids:
        msg = (
            f"{len(missing_ids)} peptide IDs in summary.tsv were not found in peptides.txt."
        )
        if logger:
            logger.warning(msg)
            logger.info(f"That's ok. Some IDs may be filter for low-confidence, so cannot be found in peptides.txt.")
        else:
            print(f"[Warning] {msg}")

def add_circ_seq_to_summary(summary_path, circ_ref_path, logger=None):
    """
    Add circRNA sequences to summary.tsv by mapping 'Fasta headers' to the given reference fasta file.
    Supports multiple headers per row separated by ';'
    """
    # Step 1: read summary.tsv
    try:
        df_summary = pd.read_csv(summary_path, sep='\t')
    except Exception as e:
        raise IOError(f"Failed to load summary file: {summary_path}\nError: {e}")

    if "Fasta headers" not in df_summary.columns:
        raise KeyError("Column 'Fasta headers' not found in summary.tsv")

    # Step 2: read fasta files and build map dict
    seq_dict = {}
    try:
        with open(circ_ref_path, 'r') as f:
            header_ids = []
            seq_lines = []
            for line in f:
                line = line.strip()
                if line.startswith(">"):
                    
                    if header_ids and seq_lines:
                        seq = "".join(seq_lines)
                        for h in header_ids:
                            seq_dict[h] = seq

                    raw_header = line[1:].strip()
                    header_ids = [h.strip() for h in raw_header.split(";") if h.strip()]
                    seq_lines = []

                else:
                    seq_lines.append(line)

            if header_ids and seq_lines:
                seq = "".join(seq_lines)
                for h in header_ids:
                    seq_dict[h] = seq

    except Exception as e:
        raise IOError(f"Failed to read fasta file: {circ_ref_path}\nError: {e}")

    # Step 3: define map function and solve multiple headers
    def map_headers_to_seqs(header_string):
        if pd.isna(header_string):
            return ""
        headers = [h.strip() for h in header_string.split(";") if h.strip()]
        seqs = [seq_dict.get(h, "") for h in headers]
        return ";".join(seqs)

    # Step 4: apply map, add new columns
    df_summary["ORF"] = df_summary["Fasta headers"].apply(map_headers_to_seqs)

    # Step 5: write file
    try:
        df_summary.to_csv(summary_path, sep='\t', index=False)
    except Exception as e:
        raise IOError(f"Failed to write updated summary file with circRNA_seq: {summary_path}\nError: {e}")

    if logger:
        logger.info(f"circRNA sequences appended to summary file: {summary_path}")

