import click
from Bio import SeqIO

@click.command()
@click.option('--circ1', "-s1", required=True, type=click.Path(exists=True), help="First full-length circRNAs (FASTA)")
@click.option('--circ2', "-s2", required=True, type=click.Path(exists=True), help="Second full-length circRNAs (FASTA)")
@click.option('--output', "-o", required=True, type=click.Path(), help="Output fasta file with merged circRNAs")

def merge_circ(circ1, circ2, output):
    """Merge shared full-length circRNAs generated by different algorithms.\n
    Example: trcirit merge-circ --circ1 circ1.fasta --circ2 circ2.fasta -o merged_circ.fasta
    """
    # Load all sequences from circ2 into a set for fast lookup
    circ2_set = set(str(rec.seq) for rec in SeqIO.parse(circ2, "fasta"))

    count_total = 0
    count_shared = 0
    with open(output, "w") as out_f:
        for rec in SeqIO.parse(circ1, "fasta"):
            count_total += 1
            if str(rec.seq) in circ2_set:
                count_shared += 1
                SeqIO.write(rec, out_f, "fasta")

    click.echo(f"Total in {circ1}: {count_total}")
    click.echo(f"Total in {circ2}: {len(circ2_set)}")
    click.echo(f"Shared sequences: {count_shared}")
    click.echo(f"Output written to: {output}")


@click.command()
def other_tools():
    """Placeholder for other tools to be added in the future."""
    click.echo("Other tools are under development.")

def add_tools_commands(cli):

    # mark merge-orf as command tools
    merge_circ.is_tool = True
    other_tools.is_tool = True

    cli.add_command(merge_circ, name="merge-circ")
    cli.add_command(other_tools, name="other-tools")
    return cli

